apiVersion: v1
description: A Helm chart for the staging hub
name: staginghub
version: 0.1.0
dependencies:
- name: jupyterhub
  version: "v0.10.6"
  repository: "https://jupyterhub.github.io/helm-chart"
