# Builds any changed docker images and pushes to Dockerhub
# If build + push runs without error, deploys to hub
#
# The bulk of this workflow happens in the deploy.py script

name: Build, push Docker image and redeploy

on:
  push:
    branches: [ staging ]
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches: [ staging ]
    paths-ignore:
    - 'docs/**'

env:
  PYTHON_VERSION: 3.8
  DOCKERHUB_USERNAME: earthlabcu
  GKE_PROJECT: ea-jupyter
  GKE_ZONE: us-central1-b
  GKE_CLUSTER: jhub

jobs:

  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: python deploy.py --build --push staginghub

  deploy:
    needs: build-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCLOUD_GH_ACTIONS }}
          project_id: ${{ env.GKE_PROJECT }}

      - uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GCLOUD_GH_ACTIONS }}

      - name: Unlock secrets dir
        uses: sliteteam/github-action-git-crypt-unlock@1.0.2
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Deploy the hub
        run: python deploy.py --deploy staginghub
