# Builds any changed docker images
# Only runs for PRs; does not push to Dockerhub or re-deploy
#
# The bulk of this workflow happens in the deploy.py script

name: Build Docker image

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

env:
  PYTHON_VERSION: 3.8
  GKE_PROJECT: ea-jupyter
  GKE_ZONE: us-central1-b
  GKE_CLUSTER: jhub2


jobs:

  build-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        hubname: [ea-hub]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # - name: Build the Docker image
      #   run: python deploy.py --build ${{matrix.hubname}}
