# Builds any changed docker images and pushes to Dockerhub
# The bulk of this workflow happens in the deploy.py script

name: Build and push Docker image

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

env:
  PYTHON_VERSION: 3.8
  DOCKERHUB_USERNAME: earthlabcu

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
